#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat $1)

filtered_msg=$(echo "$commit_msg" | grep -v '^#')
echo "커밋 메세지"
echo "$filtered_msg"

# 커밋 메세지 패턴 검사
if ! echo "$commit_msg" | grep -qE '^\[([A-Z]+-[0-9]+)\]\s+(feat|fix|docs|style|refactor|test|chore): .+'; then
    echo "❌ 잘못된 커밋 메세지 형식입니다."
    echo "
    올바른 커밋 메세지 형식:
    [ISSUE-123] feat: 회원가입 API 개발
    "
    exit 1
fi